### ISSUE TITLE
Insomnia trouble

### ISSUE THREAD

**Issue by EddyVerbruggen** [chin123/dodge-asteroids#1]
Hi, please continue the discussion here, which we started [here](https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin/issues/10).

**Comment by chin123** [comment]
Re enabled.As far as i know, this should work.

**Comment by chin123** [comment]
I tested it and it is not working. My device is still going to sleep.

**Comment by chin123** [comment]
@EddyVerbruggen Thanks a lot for all your help! It works without any issues now. I didn't realise that was the way to do it. I am still new to programming :)
